Testing pipeline

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -75,7 +75,17 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set ENVIRONMENT
-        run: echo "TF_ENV=$(echo ${{ github.head_ref }} )" >> $GITHUB_ENV
+        run: |
+          if [[ ! "${{ env.TF_ENV }}" =~ ^(devel|stage|prod) ]]; then
+            if [[ "${{ env.TF_ENV }}" =~ ^(feature|bugfix) ]]; then
+              echo "TF_ENV=$(echo 'devel' )" >> $GITHUB_ENV
+            else
+              echo "TF_ENV=$(echo ${{ github.head_ref }} )" >> $GITHUB_ENV
+            fi
+          else
+            echo "Only allow deployments from devel| stage | prod "
+            exit 0
+          fi
 
       - uses: actions/download-artifact@v4
         with:
@@ -102,17 +112,15 @@ jobs:
 
       - name: Terraform create workspace for devel
         run: |
-          if [[ ! "${{ env.TF_ENV }}" =~ ^(devel|stage|prod) ]]; then
-            if [[ "${{ env.TF_ENV }}" =~ ^(feature) ]]; then
-              terraform workspace new devel
-              terraform workspace select devel
-            else
-              terraform workspace new "${{ env.TF_ENV }}" 
-              terraform workspace select "${{ env.TF_ENV }}"
+          terraform workspace select "${{ env.TF_ENV }}"
+          exit_code=$?
+          if [ $exit_code -ne 0 ];then
+            terraform workspace new "${{ env.TF_ENV }}"
+            exit_code=$?
+            if [ $exit_code -ne 0 ];then
+              echo "Error creating the workspace"
+              exit $exit_code
             fi
-          else
-            echo "Only allow deployments from devel| stage | prod "
-            exit 0
           fi
 
       - name: Terraform Validate
@@ -121,4 +129,9 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -var env_tf="${{ env.TF_ENV }}"
+        run: |
+          terraform plan -no-color -var env_tf="${{ env.TF_ENV }}"
+
+      - name: Terraform Apply
+        run: |
+          terraform apply -no-color -var env_tf="${{ env.TF_ENV }}" -auto-approve
